// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnjyXQt72y16G8jGnT0ZoYueP6ojKSdPc',
    appId: '1:262371782138:web:4bd0670746a620d80cc843',
    messagingSenderId: '262371782138',
    projectId: 'vlad-scards',
    authDomain: 'vlad-scards.firebaseapp.com',
    storageBucket: 'vlad-scards.appspot.com',
    measurementId: 'G-B1P2Q82ZM0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMcMEUR9xBpuQuvIXiLTq9lHIs8BtxLiY',
    appId: '1:262371782138:android:fc2e0d52f79c316b0cc843',
    messagingSenderId: '262371782138',
    projectId: 'vlad-scards',
    storageBucket: 'vlad-scards.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUAkS0TkLVHxe-ZWxau8tydCRVrjGyi9o',
    appId: '1:262371782138:ios:559ded43f3b03eb00cc843',
    messagingSenderId: '262371782138',
    projectId: 'vlad-scards',
    storageBucket: 'vlad-scards.appspot.com',
    iosClientId: '262371782138-6cvj2k5popaehqu89tv06hd2b29odnpg.apps.googleusercontent.com',
    iosBundleId: 'com.example.expenceTrackerSqllite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUAkS0TkLVHxe-ZWxau8tydCRVrjGyi9o',
    appId: '1:262371782138:ios:559ded43f3b03eb00cc843',
    messagingSenderId: '262371782138',
    projectId: 'vlad-scards',
    storageBucket: 'vlad-scards.appspot.com',
    iosClientId: '262371782138-6cvj2k5popaehqu89tv06hd2b29odnpg.apps.googleusercontent.com',
    iosBundleId: 'com.example.expenceTrackerSqllite',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnjyXQt72y16G8jGnT0ZoYueP6ojKSdPc',
    appId: '1:262371782138:web:964a8dbca4f31a7d0cc843',
    messagingSenderId: '262371782138',
    projectId: 'vlad-scards',
    authDomain: 'vlad-scards.firebaseapp.com',
    storageBucket: 'vlad-scards.appspot.com',
    measurementId: 'G-T99ZTDV1K8',
  );

}